% function Hd = fir_8
% %FIR_8 Returns a discrete-time filter object.
% 
% % MATLAB Code
% % Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% % Generated on: 03-Jul-2023 19:23:19
% 
% % FIR Window Lowpass filter designed using the FIR1 function.
% 
% % All frequency values are in Hz.
% Fs = 1000;  % Sampling Frequency
% 
% N    = 7;        % Order
% Fc   = 40;      % Cutoff Frequency
% flag = 'scale';  % Sampling Flag
% 
% % Create the window vector for the design algorithm.
% win = hamming(N+1);
% 
% % Calculate the coefficients using the FIR1 function.
% b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
% Hd = dfilt.dffir(b);
% 
% % [EOF]
